# Generated by Django 4.2.1 on 2024-05-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('floor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departament_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Piso',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('floor_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('User_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Usuarios.usuarios')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
            options={
                'db_table': 'Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
            options={
                'db_table': 'Login',
                'unique_together': {('User_Id', 'day', 'hour')},
            },
        ),
    ]
