# Generated by Django 4.2.1 on 2024-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Intendencia', 'Intendencia'), ('Otro', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
