# Generated by Django 4.2.1 on 2024-05-30 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuarios', '0002_alter_cuenta_rol_alter_usuarios_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['nombres']},
        ),
        migrations.AddField(
            model_name='cuenta',
            name='apellidos',
            field=models.CharField(default='Doe', max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='edificio',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Edificio'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='nombres',
            field=models.CharField(default='John', max_length=50, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='piso',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Intendente', 'Intendencia'), ('Otro', 'Otro')], default='Otro', max_length=12, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)], verbose_name='Usuario'),
        ),
    ]
