# Generated by Django 4.2.1 on 2024-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_cuenta_options_cuenta_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='edificio',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='piso',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
