# Generated by Django 4.2.1 on 2024-05-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('unit_place', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('origins', models.CharField(max_length=255)),
                ('sold_in_pack', models.BooleanField()),
                ('quantity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('Product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Materiales.producto')),
                ('units', models.IntegerField()),
                ('umbal', models.IntegerField()),
            ],
            options={
                'db_table': 'Existencia',
            },
        ),
        migrations.CreateModel(
            name='Paquete_producto',
            fields=[
                ('Producto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Materiales.producto')),
                ('Pack_price', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
            options={
                'db_table': 'Paquete_producto',
            },
        ),
    ]
