# Generated by Django 4.2.1 on 2024-05-30 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Detalles_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reportes.solicitud')),
            ],
            options={
                'db_table': 'Detalles_solicitud',
                'unique_together': {('request', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Detalles_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reportes.pedido')),
            ],
            options={
                'db_table': 'Detalles_Pedidos',
                'unique_together': {('order', 'product_id')},
            },
        ),
    ]
